### ISSUE TITLE
release version string

### ISSUE THREAD

**Issue by BrunoRobert** [Freifunk-Greifswald/site-ffhgw#15]
The release version string should contain the git commit.
e.g. 2016.2.2~666974e

**Comment by BrunoRobert** [comment]
We will implement this soon. For now, the actual version is called 2016.3 to make an autoupdate possible (from 2016.2.x to 2016.2.2).

**Comment by schlady** [comment]
Just the date would also be sufficient. In the map the used gluon version is alsways shown.
e.g. ffhgw2016-12-27~666974e

**Comment by BrunoRobert** [comment]
Current version is 2017-02-22~73ac179.
