### ISSUE TITLE
Set mtu=1280

### ISSUE THREAD

**Issue by BrunoRobert** [Freifunk-Greifswald/site-ffhgw#6]
The problem of fragmentation is strongly discussed: [forum.freifunk.net](https://forum.freifunk.net/t/batctl-f-fragmentierung-verschlechtert-durchsatz-um-den-faktor-10/13162/31)
We should decide whether to change the mtu to 1280. This is only possible with 2 or more gateways.

**Comment by schlady** [comment]
Fixed by c342fa6c7936019b93fa87600228894185617ccd
Fastd MTU is now 1312, IPv4 and IPv6 MTU is advertised as 1280.
